# Generated by Django 2.2.3 on 2019-09-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_temperature', models.IntegerField()),
                ('actual_insolation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('source_habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Habitat')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_species', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.User')),
            ],
        ),
        migrations.CreateModel(
            name='InsolationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('source_habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Habitat')),
            ],
        ),
        migrations.AddField(
            model_name='habitat',
            name='inhabitant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Pet'),
        ),
    ]
