# Generated by Django 2.2.3 on 2019-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190917_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='habitat_type',
            field=models.CharField(default='', max_length=150),
        ),
    ]
