# Generated by Django 2.2.3 on 2019-10-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_habitat_habitat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=100)),
                ('habitat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Habitat')),
            ],
        ),
    ]
