# Generated by Django 2.2.3 on 2019-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='actual_insolation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='actual_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insolationlog',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='value',
            field=models.FloatField(),
        ),
    ]
